---
- name: Stop Kubernetes mode
  hosts: local
  gather_facts: false

  tasks:
    - name: Stop k3s service
      become: true
      ansible.builtin.systemd:
        name: k3s
        state: stopped
      failed_when: false
      changed_when: false

    - name: Kill k3s leftovers
      become: true
      ansible.builtin.command: /usr/local/bin/k3s-killall.sh
      failed_when: false
      changed_when: false

    - name: Check k3s status
      ansible.builtin.command: systemctl is-active k3s
      register: k3s_status
      failed_when: false
      changed_when: false

    - name: Show k3s status
      ansible.builtin.debug:
        msg: "k3s status: {{ k3s_status.stdout | default('unknown') }}"
