version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: postgres

    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter

    container_name: postgres-exporter

    restart: unless-stopped

    environment:
      DATA_SOURCE_NAME: "postgresql://app:app@postgres:5432/app?sslmode=disable"

    ports:
      - "9187:9187"

    depends_on:
      - postgres

  redis:
    image: redis:7

    container_name: redis

    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis-data:/data

  redis-exporter:
    image: oliver006/redis_exporter

    container_name: redis-exporter

    restart: unless-stopped

    environment:
      REDIS_ADDR: redis://redis:6379

    ports:
      - "9121:9121"

    depends_on:
      - redis

  app:
    build:
      context: ./app

    hostname: app

    container_name: spring-app

    depends_on:
      - postgres
      - redis

    restart: unless-stopped

  app2:
    build:
      context: ./app

    hostname: app2

    container_name: spring-app-2

    depends_on:
      - postgres
      - redis

    restart: unless-stopped  

  nginx:
    image: nginx:latest

    container_name: nginx

    ports:
      - "80:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - app

    restart: unless-stopped

  prometheus:
    image: prom/prometheus

    container_name: prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    depends_on:
      - app

  grafana:
    image: grafana/grafana

    container_name: grafana

    restart: unless-stopped

    depends_on:
      - prometheus

    ports:
      - "3000:3000"

    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards

volumes:
  pgdata:
  prometheus-data:
  grafana-data:
  redis-data:
