spring.datasource.url=jdbc:postgresql://postgres:5432/app
spring.datasource.username=app
spring.datasource.password=app

management.endpoints.web.exposure.include=*
management.endpoint.prometheus.access=unrestricted
management.prometheus.metrics.export.enabled=true
